"""Initial migration

Revision ID: c05fb08f1d63
Revises: 8bf1a32eb9e3
Create Date: 2024-06-25 17:24:14.141979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05fb08f1d63'
down_revision: Union[str, None] = '8bf1a32eb9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
    sa.Column('NAME', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('NAME')
    )
    op.create_table('security_trades',
    sa.Column('Security_Id', sa.String(), nullable=False),
    sa.Column('Tradeno', sa.Integer(), nullable=False),
    sa.Column('Tradetime', sa.Time(), nullable=False),
    sa.Column('Boardid', sa.String(), nullable=False),
    sa.Column('Prise', sa.Double(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Value', sa.Double(), nullable=False),
    sa.Column('Period', sa.String(), nullable=False),
    sa.Column('Yied', sa.Double(), nullable=False),
    sa.Column('Tradetime_grp', sa.Integer(), nullable=False),
    sa.Column('Systime', sa.DateTime(), nullable=False),
    sa.Column('Buysell', sa.String(), nullable=False),
    sa.Column('Decimals', sa.Integer(), nullable=False),
    sa.Column('Tradingsession', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Tradeno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_trades')
    op.drop_table('security')
    # ### end Alembic commands ###
